ARG NODE_VERSION="20.17.0"
ARG PNPM_VERSION="10.13.1"

##
# Create base image with pnpm installed 
##

FROM node:${NODE_VERSION}-alpine as sample-pnpm
LABEL sample/pnpm-monorepo-template.name=pnpm

RUN apk add git
RUN apk add --no-cache --upgrade grep
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
  npm i -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY ["./*.json", "./*.yaml", "./"]
